#!/usr/bin/python3
"""Adds a new state 'Louisiana' to the database"""

# For details on why each import please confer previous task.
import sys
from sqlalchemy import (create_engine)
from model_state import Base, State
from sqlalchemy.orm import sessionmaker
from sqlalchemy import func  # Required to guarantee case-sensitive LIKE.


if __name__ == "__main__":
    """Adding a new state 'Louisiana'"""
    db_user = sys.argv[1] if len(sys.argv) > 1 else 'root'
    db_passwd = sys.argv[2] if len(sys.argv) > 2 else 'root'
    db_name = sys.argv[3] if len(sys.argv) > 3 else 'hbtn_0e_6_usa'
    engine = create_engine(
        'mysql+mysqldb://{}:{}@localhost/{}'
        .format(db_user, db_passwd, db_name),
        # echo=True,  # Activates "verbose mode" for engine
        pool_pre_ping=True
    )

    # Create a Session class which can then "spawn" transactional objects.
    Session = sessionmaker(bind=engine)
    # Create a new "channel" to query database.
    state_adder = Session()
    # Normally we'd check the argument far earlier
    state_to_add = "Louisiana"

    # Note: I didn't specify 'id' since it must be generated by SQL itself.
    new_state = State(name="Louisiana")
    # Session object silently starts a SQL "Transaction" but does NOT commit.
    state_adder.add(new_state)
    # Committing requires explicit order to do so.
    # Benefit of this is being able to add many other data manipulations
    #   in the same transaction (modifying object, adding others etc).
    state_adder.commit()
    # Now our new state has its id.
    print(new_state.id)

    # Preferred over session.query(State).order_by(State.id).limit(1).all()
    #  because the latter would return a list whatever the limit number is
    #  (and whether or not there are actual results) thus forcing the use
    #  of a loop to manually "unwrap" each element.
